
name: Pypypy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DISPLAY: ":99.0"

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install selenium

    - name: Install xvfb
      run: sudo apt-get install -y xvfb

    - name: Check xvfb version
      run: xvfb-run --version

    - name: Start xvfb and run tests
      run: |
        xvfb-run --auto-servernum --server-args="-screen 0 1024x768x24"

